FROM golang:1.13.0
WORKDIR /go/src/github.com/debarshibasak/kubestrike/
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o kubestrike .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/debarshibasak/kubestrike/kubestrike .
CMD ["./kubestrike"]