apiVersion: v1
kind: CreateCluster
provider: Multipass
clusterName: testcluster
kubeadm:
  networking:
    podCidr: 10.233.0.0/18
    serviceCidr: 10.233.64.0/18
    plugin: flannel
multipass:
  masterCount: 1
  workerCount: 1
