apiVersion: v1
kind: CreateCluster
provider: Multipass
clusterName: testcluster
k3s:
  docker: true
  networking:
    podCidr: 10.233.0.0/18
    serviceCidr: 10.233.64.0/18
    backend: vxlan
multipass:
  masterCount: 1
  workerCount: 1
