apiVersion: v1
kind: CreateCluster
clusterName: test
baremetal:
  master:
    - ip: "192.168.64.13"
  worker:
    - ip: "192.168.64.15"
    - ip: "192.168.64.14"
  keyLocation: /Users/debarshibasak/.ssh/id_rsa
  username: ubuntu
k3s:
  networking:
    backend: vxlan
    podCidr: 10.233.0.0/18
    serviceCidr: 10.233.64.0/18
